package com.lsc.personal.tools.db.mapper;

import com.lsc.personal.tools.db.dao.QrtzLocks;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface QrtzLocksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("schedName") String schedName, @Param("lockName") String lockName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    int insert(QrtzLocks record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qrtz_locks
     *
     * @mbggenerated
     */
    List<QrtzLocks> selectAll();
}